FROM kmpm/fritzbuild-base:latest

USER root
ARG APT_INSTALL="apt-get -qq install -y --no-install-recommends --no-install-suggests -o=Dpkg::Use-Pty=0"
ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get -qq update \
    && ${APT_INSTALL} \
    libgl1-mesa-dev \
    ninja-build generate-ninja \
    libvulkan-dev vulkan-tools \
    libdrm-dev \
    libinput-dev libts-dev \
    libxcb-render-util0-dev \
    libxcb-render0-dev \
    libxcb-shape0-dev \
    libxcb-randr0-dev \
    libxcb-xfixes0-dev \
    libxcb-xkb-dev \
    libxcb-sync-dev \
    libxcb-shm0-dev \
    libxcb-icccm4-dev \
    libxcb-keysyms1-dev \
    libxcb-image0-dev \
    libxcb-util-dev \
    libxcb-cursor-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    libfontconfig-dev \
    libfreetype-dev \
    libxext-dev \
    libx11-dev \
    libx11-xcb-dev \
    libxcb1-dev \
    libsm-dev \
    libice-dev \
    libglib2.0-dev \
    # cleanup
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER bob