FROM debian:bookworm-slim

ARG APT_INSTALL="apt-get -qq install -y --no-install-recommends --no-install-suggests -o=Dpkg::Use-Pty=0"

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8

RUN apt-get -qq update \
    && apt-get -qq upgrade -y \
    && ${APT_INSTALL} \
    autoconf \
    automake \
    bison \
    build-essential \
    bzip2 \
    ca-certificates \
    checkinstall \
    cmake \
    flex \
    git \
    gzip \
    libfontconfig1 \
    libreadline-dev \
    libssl-dev \
    libtool \
    libx11-dev \
    libxaw7-dev \
    libxext-dev \
    libxft-dev \
    libxmu-dev \
    libxpm-dev \
    libxt-dev \
    locales \
    sudo \
    tar \
    wget \
    xz-utils \
    # fritzing guestimated dependencies
    libboost-dev \
    libboost-all-dev \
    libgit2-dev \
    libjpeg-dev \
    libncurses5-dev \
    libpng-dev \
    #libqt6serialport6-dev \
    #libqt6svg6-dev \
    #libquazip1-qt6-dev \
    libssl-dev \
    libudev-dev \
    libz-dev \
    python3-dev \
    #qconf \
    #qmake6 \
    #qt6-5compat-dev \
    #qt6-base-dev \
    #qt6-tools-dev-tools \
    xvfb \
    # cleanup
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    

RUN ldconfig -C /etc/ld.so.cache \
    && sed -i -e "s/# $LANG.*/$LANG UTF-8/" /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=$LANG

# Bob the Builder :)
ARG USERNAME=bob    

RUN useradd -m -s /bin/bash ${USERNAME} \
    && echo "${USERNAME}:${USERNAME}" | chpasswd \
    && adduser ${USERNAME} sudo \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers 

USER ${USERNAME}
WORKDIR /home/${USERNAME}
